### ISSUE TITLE
trying to do your flask tutorial

### ISSUE THREAD

**Issue by gswscreagle** [prakhar1989/docker-curriculum#310]
was trying to do your flask tutorial and it's not working for me...not sure why. This is what I was getting when trying to fire it up

gwilliams@alice:~/src/docker-curriculum/flask-app$ sudo docker run -p 8888:5000 gswscreagle/catnip
Traceback (most recent call last):
  File "/usr/src/app/./app.py", line 1, in <module>
    from flask import Flask, render_template
  File "/usr/local/lib/python3.10/site-packages/flask/__init__.py", line 21, in <module>
    from .app import Flask, Request, Response
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 34, in <module>
    from .sessions import SecureCookieSessionInterface
  File "/usr/local/lib/python3.10/site-packages/flask/sessions.py", line 14, in <module>
    from collections import MutableMapping
ImportError: cannot import name 'MutableMapping' from 'collections' (/usr/local/lib/python3.10/collections/__init__.py)

my email address is ggrantsw@gmail.com

**Comment by blessed2142** [comment]
Hello, just change python version on your Dockerfile. 
FROM python:3.9 worked fine for me)

**Comment by demndevel** [comment]
you can change requirements.txt to 
```Flask==2.0
itsdangerous==2.0.1
```

**Comment by prakhar1989** [comment]
Fixed in https://github.com/prakhar1989/docker-curriculum/pull/313

**Comment by prakhar1989** [comment]
Thank you for reporting this issue! We have recently updated the Flask tutorial application to Python 3.12-slim and resolved all dependency pins in https://github.com/prakhar1989/docker-curriculum/commit/1ac2bde324e2ba36b7f529140ec35591713be01d. Closing this issue now.
