### ISSUE TITLE
error running catnip...

### ISSUE THREAD

**Issue by carterm2** [prakhar1989/docker-curriculum#319]
Hi, 
Thanks for the tutorial on docker... I get the following message... (running python3.9 there is no python3..10 directory)

docker run -p 8888:5000 cartervm2/catnip2
Traceback (most recent call last):
  File "/usr/src/app/./app.py", line 1, in <module>
    from flask import Flask, render_template
  File "/usr/local/lib/python3.10/site-packages/flask/__init__.py", line 21, in <module>
    from .app import Flask, Request, Response
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 34, in <module>
    from .sessions import SecureCookieSessionInterface
  File "/usr/local/lib/python3.10/site-packages/flask/sessions.py", line 14, in <module>
    from collections import MutableMapping
ImportError: cannot import name 'MutableMapping' from 'collections' (/usr/local/lib/python3.10/collections/__init__.py)

Thx, 

Carter

**Comment by 54D** [comment]
See: #308 and #313

For a quick fix, in Dockerfile change:
```dockerfile
FROM python:3.6
```

**Comment by prakhar1989** [comment]
Fixed in https://github.com/prakhar1989/docker-curriculum/pull/313
