### ISSUE TITLE
Creating catnip image

### ISSUE THREAD

**Issue by smalluk** [prakhar1989/docker-curriculum#323]
When trying to run the docker image we create early on with catnip i am getting a python error:

Traceback (most recent call last):
  File "/usr/src/app/./app.py", line 1, in <module>
    from flask import Flask, render_template
  File "/usr/local/lib/python3.10/site-packages/flask/__init__.py", line 21, in <module>
    from .app import Flask, Request, Response
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 34, in <module>
    from .sessions import SecureCookieSessionInterface
  File "/usr/local/lib/python3.10/site-packages/flask/sessions.py", line 14, in <module>
    from collections import MutableMapping
ImportError: cannot import name 'MutableMapping' from 'collections' (/usr/local/lib/python3.10/collections/__init__.py)

**Comment by prakhar1989** [comment]
https://github.com/prakhar1989/docker-curriculum/pull/313
