### ISSUE TITLE
ImportError raised when running catnip example

### ISSUE THREAD

**Issue by yis11178** [prakhar1989/docker-curriculum#328]
The following error is raised when I tried to run the catnip example under section `Dockerfile`:

```
Traceback (most recent call last):
  File "/usr/src/app/./app.py", line 1, in <module>
    from flask import Flask, render_template
  File "/usr/local/lib/python3.10/site-packages/flask/__init__.py", line 21, in <module>
    from .app import Flask, Request, Response
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 34, in <module>
    from .sessions import SecureCookieSessionInterface
  File "/usr/local/lib/python3.10/site-packages/flask/sessions.py", line 14, in <module>
    from collections import MutableMapping
ImportError: cannot import name 'MutableMapping' from 'collections' (/usr/local/lib/python3.10/collections/__init__.py)
```

 This can be solved by changing the following line from the sample `Dockerfile`

```
FROM python:3
```

into

```
FROM python:3.9
```

**Comment by 54D** [comment]
See #313

**Comment by prakhar1989** [comment]
Thank you for reporting this issue! We have recently updated the Flask tutorial application to Python 3.12-slim and resolved all dependency pins in https://github.com/prakhar1989/docker-curriculum/commit/1ac2bde324e2ba36b7f529140ec35591713be01d. Closing this issue now.
