### ISSUE TITLE
Upgrade Flask from 1.0 to >= 2.0.1 in requirements.txt

### ISSUE THREAD

**Issue by peterdyoon** [prakhar1989/docker-curriculum#334]
When running `docker run -p 8888:5000 yourusername/catnip`, I got the following error:

```
Traceback (most recent call last):
  File "/usr/src/app/./app.py", line 1, in <module>
    from flask import Flask, render_template
  File "/usr/local/lib/python3.10/site-packages/flask/__init__.py", line 21, in <module>
    from .app import Flask, Request, Response
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 25, in <module>
    from . import cli, json
  File "/usr/local/lib/python3.10/site-packages/flask/json/__init__.py", line 21, in <module>
    from itsdangerous import json as _json
ImportError: cannot import name 'json' from 'itsdangerous' (/usr/local/lib/python3.10/site-packages/itsdangerous/__init__.py)
```

[Based on this website](https://exerror.com/importerror-cannot-import-name-json-from-itsdangerous/#:~:text='%20from%20'itsdangerous'-,To%20Solve%20ImportError%3A%20cannot%20import%20name%20'json'%20from%20',it%20will%20solve%20your%20error.), it seems Flask needs to be upgraded to at least 2.0.1 in the requirements.txt file to make the import work.

Thanks for this tutorial! It's super helpful :)

**Comment by peterdyoon** [comment]
Just saw https://github.com/prakhar1989/docker-curriculum/issues/332; closing this one.
