### ISSUE TITLE
Issue with install markupsafe

### ISSUE THREAD

**Issue by lgriger-git** [prakhar1989/docker-curriculum#363]
Hi I had issue with build docker image in section Multi Container, below is error.
Issue was fixed when I changed in Dockerfile ubuntu version from 18 to 20.

/#14 7.919 Collecting MarkupSafe>=2.0 (from Jinja2>=2.10.1->Flask==1.1.2->-r requirements.txt (line 2))
#14 8.334   Downloading https://files.pythonhosted.org/packages/bf/10/ff66fea6d1788c458663a84d88787bae15d45daa16f6b3ef33322a51fc7e/MarkupSafe-2.0.1.tar.gz
#14 8.514     Complete output from command python setup.py egg_info:
#14 8.514     Traceback (most recent call last):
#14 8.514       File "<string>", line 1, in <module>
#14 8.514       File "/tmp/pip-build-ucchxhu8/MarkupSafe/setup.py", line 61, in <module>
#14 8.514         run_setup(True)
#14 8.514       File "/tmp/pip-build-ucchxhu8/MarkupSafe/setup.py", line 44, in run_setup
#14 8.514         ext_modules=ext_modules if with_binary else [],
#14 8.514       File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 129, in setup
#14 8.514         return distutils.core.setup(**attrs)
#14 8.514       File "/usr/lib/python3.6/distutils/core.py", line 121, in setup
#14 8.514         dist.parse_config_files()
#14 8.514       File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 494, in parse_config_files
#14 8.514         ignore_option_errors=ignore_option_errors)
#14 8.514       File "/usr/lib/python3/dist-packages/setuptools/config.py", line 106, in parse_configuration
#14 8.514         meta.parse()
#14 8.514       File "/usr/lib/python3/dist-packages/setuptools/config.py", line 382, in parse
#14 8.514         section_parser_method(section_options)
#14 8.514       File "/usr/lib/python3/dist-packages/setuptools/config.py", line 355, in parse_section
#14 8.514         self[name] = value
#14 8.514       File "/usr/lib/python3/dist-packages/setuptools/config.py", line 173, in __setitem__
#14 8.514         value = parser(value)
#14 8.514       File "/usr/lib/python3/dist-packages/setuptools/config.py", line 430, in _parse_version
#14 8.514         version = self._parse_attr(value)
#14 8.514       File "/usr/lib/python3/dist-packages/setuptools/config.py", line 305, in _parse_attr
#14 8.514         module = import_module(module_name)
#14 8.514       File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
#14 8.514         return _bootstrap._gcd_import(name[level:], package, level)
#14 8.514       File "<frozen importlib._bootstrap>", line 994, in _gcd_import
#14 8.514       File "<frozen importlib._bootstrap>", line 971, in _find_and_load
#14 8.514       File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
#14 8.514     ModuleNotFoundError: No module named 'markupsafe'
#14 8.514     
#14 8.514     ----------------------------------------
#14 8.526 Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-ucchxhu8/MarkupSafe/
/

**Comment by NicolasCwy** [comment]
Found a solution from a closed issue https://github.com/prakhar1989/docker-curriculum/issues/352

`open FoodTrucks/Dockerfile insert RUN apt-get install -y python3-markupsafe before RUN npm install
It was posted previously by Halpert3. thx.`

**Comment by emiliodacosta** [comment]
just encountered same issue

**Comment by prakhar1989** [comment]
Thank you for reporting this issue! We have recently updated the Flask tutorial application to Python 3.12-slim and resolved all dependency pins in https://github.com/prakhar1989/docker-curriculum/commit/1ac2bde324e2ba36b7f529140ec35591713be01d. Closing this issue now.
