### ISSUE TITLE
[BUG] Dockerfile section of tutorial

### ISSUE THREAD

**Issue by oseba** [prakhar1989/docker-curriculum#382]
The bug :
If we follow the instructions, we end with the following error when we try the command _docker run -p 8888:5000 yourusername/catnip_

`Traceback (most recent call last):
  File "./app.py", line 1, in <module>
    from flask import Flask, render_template
  File "/usr/local/lib/python3.8/site-packages/flask/__init__.py", line 7, in <module>
    from .app import Flask as Flask
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 28, in <module>
    from . import cli
  File "/usr/local/lib/python3.8/site-packages/flask/cli.py", line 18, in <module>
    from .helpers import get_debug_flag
  File "/usr/local/lib/python3.8/site-packages/flask/helpers.py", line 16, in <module>
    from werkzeug.urls import url_quote
ImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/usr/local/lib/python3.8/site-packages/werkzeug/urls.py)
`

To reproduce the error, one may simply follow the tutorial and execute the concerned command above.
We have this error, because the installed version of "Werkzeug" is not compatible with the lastest version Flask.
To fix this problem, we may add the following line in "the requirements.txt" of the project  _https://github.com/prakhar1989/docker-curriculum.git_  : 
Werkzeug==2.2.2 this version works fine with flash. (Didn't check which latest version we can use but this one works)

 - OS: Ubuntu 22.04.3 LTS
 - Docker Version 20.10.22

Thank you
Best Regards
OS

**Comment by prakhar1989** [comment]
Thank you for reporting this issue! We have recently updated the Flask tutorial application to Python 3.12-slim and resolved all dependency pins in https://github.com/prakhar1989/docker-curriculum/commit/1ac2bde324e2ba36b7f529140ec35591713be01d. Closing this issue now.
