### ISSUE TITLE
werkzeug.urls Error when following along with the "Webapps with Docker" part of the Tutorial

### ISSUE THREAD

**Issue by saclark91** [prakhar1989/docker-curriculum#386]
Received this error when trying to follow along with the catnip application steps in the Docker Tutorial for Beginners guide

```
$ docker run -p 8888:5000 yourusername/catnip
Traceback (most recent call last):
  File "./app.py", line 1, in <module>
    from flask import Flask, render_template
  File "/usr/local/lib/python3.8/site-packages/flask/__init__.py", line 7, in <module>
    from .app import Flask as Flask
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 28, in <module>
    from . import cli
  File "/usr/local/lib/python3.8/site-packages/flask/cli.py", line 18, in <module>
    from .helpers import get_debug_flag
  File "/usr/local/lib/python3.8/site-packages/flask/helpers.py", line 16, in <module>
    from werkzeug.urls import url_quote
ImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/usr/local/lib/python3.8/site-packages/werkzeug/urls.py)
```

After I did some digging setting `Werkzeug==2.2.2` in **requirements.txt** was able to make it work.

Not sure if that is an appropriate fix, or just a workaround.  I wanted to submit it just in case other users are running in to the same problem.

**Comment by prakhar1989** [comment]
Thank you for reporting this issue! We have recently updated the Flask tutorial application to Python 3.12-slim and resolved all dependency pins in https://github.com/prakhar1989/docker-curriculum/commit/1ac2bde324e2ba36b7f529140ec35591713be01d. Closing this issue now.
