### ISSUE TITLE
Werkzeug version ImportError 

### ISSUE THREAD

**Issue by wmauz** [prakhar1989/docker-curriculum#387]
Got error when running docker run <user>/catnip. Fixed it by updating Werkzueg version to 2.2.2 in requirements.txt.
Seems to be a missmatch between Flask and Werkzeug versions.

ERROR:
Traceback (most recent call last):
  File "./app.py", line 1, in <module>
    from flask import Flask, render_template
  File "/usr/local/lib/python3.8/site-packages/flask/__init__.py", line 7, in <module>
    from .app import Flask as Flask
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 28, in <module>
    from . import cli
  File "/usr/local/lib/python3.8/site-packages/flask/cli.py", line 18, in <module>
    from .helpers import get_debug_flag
  File "/usr/local/lib/python3.8/site-packages/flask/helpers.py", line 16, in <module>
    from werkzeug.urls import url_quote
ImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/usr/local/lib/python3.8/site-packages/werkzeug/urls.py)

**Comment by MichaelWStuart** [comment]
Update the flask version in `requirements.tsx`

**Comment by william2032** [comment]
Hello ,I tried the solution stated above but didn't work.So tried deleting the my  docker image and recreating it again and worked for me.
Flask==3.0.0
Werkzeug==3.0.0

**Comment by prakhar1989** [comment]
Thank you for reporting this issue! We have recently updated the Flask tutorial application to Python 3.12-slim and resolved all dependency pins in https://github.com/prakhar1989/docker-curriculum/commit/1ac2bde324e2ba36b7f529140ec35591713be01d. Closing this issue now.
