### ISSUE TITLE
Missing requirement in flask app [BUG]

### ISSUE THREAD

**Issue by bar2011** [prakhar1989/docker-curriculum#391]
**Bug Description**
When building the flask-app Dockerfile there seems to be no problem, but after running a container created from it, it shows the following error:
`Traceback (most recent call last):
  File "./app.py", line 1, in <module>
    from flask import Flask, render_template
  File "/usr/local/lib/python3.8/site-packages/flask/__init__.py", line 7, in <module>
    from .app import Flask as Flask
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 28, in <module>
    from . import cli
  File "/usr/local/lib/python3.8/site-packages/flask/cli.py", line 18, in <module>
    from .helpers import get_debug_flag
  File "/usr/local/lib/python3.8/site-packages/flask/helpers.py", line 16, in <module>
    from werkzeug.urls import url_quote
ImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/usr/local/lib/python3.8/site-packages/werkzeug/urls.py)`
**Bug Fix**
Add `Werkzeug==2.2.2` to /flask-app/requirements.txt

**Comment by IIIphr** [comment]
Adding `Werkzeug` to the dependencies fixed it for me. My `requirements.txt` now looks like this:
```
Werkzeug==2.3.8
Flask==2.0.2
```

**Comment by prakhar1989** [comment]
Thank you for reporting this issue! We have recently updated the Flask tutorial application to Python 3.12-slim and resolved all dependency pins in https://github.com/prakhar1989/docker-curriculum/commit/1ac2bde324e2ba36b7f529140ec35591713be01d. Closing this issue now.
