### ISSUE TITLE
Docker build fail to run for docker-curriculum

### ISSUE THREAD

**Issue by zurialzurial** [prakhar1989/docker-curriculum#392]
Hi Prakhar,

I am a newbie for Docker and I am really enjoying your website.  Your website is very helpful for a beginner like me with theories and so practical as well.

However, I have a problem when running the docker-curriculum with the below error message.

docker run -p 8888:5000 xxxx/catnip
Traceback (most recent call last):
  File "./app.py", line 1, in <module>
    from flask import Flask, render_template
  File "/usr/local/lib/python3.8/site-packages/flask/__init__.py", line 7, in <module>
    from .app import Flask as Flask
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 28, in <module>
    from . import cli
  File "/usr/local/lib/python3.8/site-packages/flask/cli.py", line 18, in <module>
    from .helpers import get_debug_flag
  File "/usr/local/lib/python3.8/site-packages/flask/helpers.py", line 16, in <module>
    from werkzeug.urls import url_quote
ImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/usr/local/lib/python3.8/site-packages/werkzeug/urls.py)

I am not sure what is the issue, as I am just following your instruction.  

I will be very appreciated if you can guide me.

thank you.

Regards,
Zurial

**Comment by todo** [comment]
The problem is caused by docker build system pull in the newer Werkzeug pkg (probably 3.x.x). In new werkzeug version there is no "url_encode'.

Just add the following line to your requirements.txt, then rebuild your image, it'll fix your problem

Werkzeug==2.2.2

**Comment by prakhar1989** [comment]
Thank you for reporting this issue! We have recently updated the Flask tutorial application to Python 3.12-slim and resolved all dependency pins in https://github.com/prakhar1989/docker-curriculum/commit/1ac2bde324e2ba36b7f529140ec35591713be01d. Closing this issue now.
