### ISSUE TITLE
Unexpected error

### ISSUE THREAD

**Issue by OmarCode996** [prakhar1989/docker-curriculum#398]
Hi

when i ever i try to follow the guide and try to do the steps , I encounter an error as follows:

Traceback (most recent call last):
  File "./app.py", line 1, in <module>
    from flask import Flask, render_template
  File "/usr/local/lib/python3.8/site-packages/flask/__init__.py", line 7, in <module>
    from .app import Flask as Flask
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 28, in <module>
    from . import cli
  File "/usr/local/lib/python3.8/site-packages/flask/cli.py", line 18, in <module>
    from .helpers import get_debug_flag
  File "/usr/local/lib/python3.8/site-packages/flask/helpers.py", line 16, in <module>
    from werkzeug.urls import url_quote
ImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/usr/local/lib/python3.8/site-packages/werkzeug/urls.py)

when i searched online it suggested that there is a version incompatibility between the werkzeug and the flask library I am new to this so I dont know what to do

**Comment by Plagiatus** [comment]
see #387

**Comment by prakhar1989** [comment]
Thank you for reporting this issue! We have recently updated the Flask tutorial application to Python 3.12-slim and resolved all dependency pins in https://github.com/prakhar1989/docker-curriculum/commit/1ac2bde324e2ba36b7f529140ec35591713be01d. Closing this issue now.
