### ISSUE TITLE
run docker fails 

### ISSUE THREAD

**Issue by yoshiomi999** [prakhar1989/docker-curriculum#403]
To create docker image of Cat gif, it needed add a new line:   Werkzeug==2.3.7 inside flask-app > requirements.txt 
It was not enough only Flask==2.0.2

**Comment by kaimmej** [comment]
### Problem
In the Dockerfile section of the guide, specifically when I went to Run my first docker container. 
I received error messages related to Werkzeurg, Jinja2 and itsdangerous. 

### Solution (I think)
My requirments.txt file ended up needing to be the following:
Flask==1.1.2
Werkzeug==1.0.1
Jinja2==3.0.3
itsdangerous==1.1.0


### Error
Example error message from itsdangerous import error

docker run -p 8888:5000 {myUserNameDeletedForPrivacy}/catnip
Traceback (most recent call last):
  File "./app.py", line 1, in <module>
    from flask import Flask, render_template
  File "/usr/local/lib/python3.8/site-packages/flask/__init__.py", line 19, in <module>
    from . import json
  File "/usr/local/lib/python3.8/site-packages/flask/json/__init__.py", line 15, in <module>
    from itsdangerous import json as _json
ImportError: cannot import name 'json' from 'itsdangerous' (/usr/local/lib/python3.8/site-packages/itsdangerous/__init__.py)

**Comment by prakhar1989** [comment]
Thank you for reporting this issue! We have recently updated the Flask tutorial application to Python 3.12-slim and resolved all dependency pins in https://github.com/prakhar1989/docker-curriculum/commit/1ac2bde324e2ba36b7f529140ec35591713be01d. Closing this issue now.
