### ISSUE TITLE
I got an error when I ran "docker run -p 8888:5000 ratbek/catnip"

### ISSUE THREAD

**Issue by raaliev-dev** [prakhar1989/docker-curriculum#407]
When I ran command  "docker run -p 8888:5000 ratbek/catnip", I got an error like below:
Traceback (most recent call last):
  File "./app.py", line 1, in <module>
    from flask import Flask, render_template
  File "/usr/local/lib/python3.8/site-packages/flask/__init__.py", line 7, in <module>
    from .app import Flask as Flask
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 28, in <module>
    from . import cli
  File "/usr/local/lib/python3.8/site-packages/flask/cli.py", line 18, in <module>
    from .helpers import get_debug_flag
  File "/usr/local/lib/python3.8/site-packages/flask/helpers.py", line 16, in <module>
    from werkzeug.urls import url_quote
ImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/usr/local/lib/python3.8/site-packages/werkzeug/urls.py)

I did everything as indicated in the tutorial. How to resolve this issue? Help me

**Comment by raaliev-dev** [comment]
The issue is resolved. I removed all docker data, that is containers, images, caches by "docker system prune -a -f". And added in requirments.txt lines like below
Flask==3.0.0
Werkzeug==3.0.0

Then I built again and ran again. And it's worked as expected.
